### ISSUE TITLE
useParams strict:false - no types available (as of 1.6.0)

### ISSUE THREAD

**Issue by austinm911** [TanStack/router#1030]
### Describe the bug

When using `useParams({ strict: false })`, it looks like the type safety was lost

This is as of 1.6.0

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-yzcrtv?file=src/routes/posts.$postId.tsx

### Steps to Reproduce the Bug or Issue

Destructure postId from useParams. No type safety is available. You can see the console log with the post Id in the repro when navigating to a Post ID route.

### Expected behavior

Expect postId to be available to destructure

### Platform

macOS, Arc

**Comment by ctjhoa** [comment]
I confirm this issue, `useParams` isn't usable without Route at the moment.
I also want to point out that `useParams` documentation seems weird/wrong to me.
https://tanstack.com/router/v1/docs/api/router/useParamsHook

Here is the current example:
```ts
import { useParams } from '@tanstack/react-router'

function Component() {
  const params = myRoute.useParams({ from: '/posts/$postId' })

  // OR

  const postId = myRoute.useParams({
    from: '/posts/$postId',
    select: (params) => params.postId,
  })

  // OR

  const looseParams = myRoute.useParams({ strict: false })
}
```

First, I don't see why you need to specify a `from` parameter when you already invoke the `myRoute.useParams`.
Then, `myRoute.useParams({ strict: false })` doesn't make sense because if you have access to the route, bypassing typecheck should be a bad practice.
IMO example should be the following

 ```ts
import { useParams } from '@tanstack/react-router'

function Component() {
  const params = myRoute.useParams()

  // OR
  
  const params = useParams({ from: '/posts/$postId' })

  // OR

  const postId = useParams({
    from: '/posts/$postId',
    select: (params) => params.postId,
  })

  // OR

  const looseParams = useParams({ strict: false })
}
```

**Comment by sAtluna** [comment]
@ctjhoa, adding the functionality of using just `useParams` back without the need for any `Route` would be highly appreciated

**Comment by schiller-manuel** [comment]
@ctjhoa can you please submit a PR that fixes this doc issue?

**Comment by schiller-manuel** [comment]
we just released v.1.9.0 which added the `experimental_returnIntersection` option for various hooks (including `useSearch` and `useParams`)
this option can be used in combination with `strict: false` like this:

```tsx
const params = useParams({experimental_returnIntersection:true, strict:false})`;
```

The type of params will then be a partial intersection of all path parameters instead of the union of all route path parameters.

Please give us feedback so we can make this a stable API soon.
