### ISSUE TITLE
404 route is not rendered in child routes that doesn't exists

### ISSUE THREAD

**Issue by GiancarlosIO** [TanStack/router#1038]
### Describe the bug

I have two urls
- /
- /about

I have configured the [not-found url](https://tanstack.com/router/v1/docs/guide/creating-a-router#not-found-route) but when I go to urls like `/about/asdfsadf` it renders the about page instead of the 404 error 😢 

### Your Example Website or App

https://stackblitz.com/edit/github-7h7yen?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to https://stackblitz.com/edit/github-7h7yen?file=src%2Fmain.tsx
2. Click on the link About/not-found
3. The about page is rendered instead of the 404 component

### Expected behavior

The not found route should be rendered.

### Screenshots or Videos

Here we can see the devtools where the `/about` and `/404` routes are matches which maybe its wrong because my url is not a Splat / Catch-All Routes 😢 

![image](https://github.com/TanStack/router/assets/17274950/d3090259-6892-4215-a677-cb702d99328c)

### Platform

- OS:  Windows
- Browser: Chrome
- Version: 1.6

**Comment by gjtiquia** [comment]
I am facing this issue as well!

Currently using `@tanstack/react-router` version `1.10.0`, here is my code for setting up the router

```ts
import { createRouter, createHashHistory, NotFoundRoute } from '@tanstack/react-router';
import { routeTree } from '../../routeTree.gen'
import { Route as RootRoute } from '@/routes/__root'
import { NotFoundPage } from '@/features/NotFoundPage';

const hashHistory = createHashHistory();

export const router = createRouter({
    routeTree,
    history: hashHistory,
    notFoundRoute: new NotFoundRoute({
        getParentRoute: () => RootRoute,
        component: () => <NotFoundPage />
    })
});
```

Using file based routing, with the latest best practices from the latest docs (eg. `createRootRoute` instead of `new RootRoute`).

Here is the commit with my current setup
https://github.com/gjtiquia/mini-link-stash/tree/7d115dd1dae216125a1af0f7311a4e66d92b64c8 

Temporarily deployed this commit here
https://deploy-preview-1--mini-link-stash.netlify.app/ 

Pasting the following url goes to the `/about` route
https://deploy-preview-1--mini-link-stash.netlify.app/#/about

Pasting the following url shows `404` page not found
https://deploy-preview-1--mini-link-stash.netlify.app/#/ajshdgfbasdukhfgbhjkasd

However, same as @GiancarlosIO, pasting the following url goes to the `/about` route instead of `404`
https://deploy-preview-1--mini-link-stash.netlify.app/#/about/ajshdgfbasdukhfgbhjkasd

**Comment by gjtiquia** [comment]
I couldn't find a concrete code example in the docs demonstrating how to setup the `notFoundRoute` in the router.

In my own code, and in @GiancarlosIO 's code in the link above, the `getParentRoute` property of `NotFoundRoute` is set to the root route. 

Perhaps this is where the bug occured? Because routes that are directly under the root route (eg. `/this-path-does-not-exist`) will go to the 404 page, while routes that are in other children routes (eg. `/the-children-path/this-path-does-not-exist`) goes to the children route instead (eg. `/the-children-path`)

**Comment by gjtiquia** [comment]
Found the code example in the docs from this discussion: https://github.com/TanStack/router/discussions/1013

Link to the docs: https://tanstack.com/router/v1/docs/framework/react/guide/creating-a-router#not-found-route

The code snippet from the docs shown below:

File based routing
```ts
import { NotFoundRoute } from '@tanstack/react-router'
import { Route as rootRoute } from './routes/__root.tsx'

const notFoundRoute = new NotFoundRoute({
  getParentRoute: () => rootRoute,
  component: () => '404 Not Found',
})

const router = createRouter({
  routeTree,
  notFoundRoute,
})
```

Code based routing
```ts
import { NotFoundRoute } from '@tanstack/react-router'

const rootRoute = createRootRoute()

// ...

const notFoundRoute = new NotFoundRoute({
  getParentRoute: () => rootRoute,
  component: () => '404 Not Found',
})

const router = createRouter({
  routeTree,
  notFoundRoute,
})
```

Which is the same as how I set it up previously. Still does not work for child routes.

**Comment by gjtiquia** [comment]
The issue can also be reproduced in the basic example from the source code
https://github.com/TanStack/router/tree/main/examples/react/basic 
Reproduced at commit 77955ab in the main branch

Going to `/non-existent-route`  shows 404 - Not Found
![image](https://github.com/TanStack/router/assets/47134711/c63ededd-77a7-44ba-bf4a-1eb5ec3007c2)

Going to `/posts/1` shows post 1
![image](https://github.com/TanStack/router/assets/47134711/f5c27fd4-2ebd-4fd0-9766-2091273552d4)

Going to `/posts/1/non-existent-route` shows post 1, but we should expect 404 - Not Found
![image](https://github.com/TanStack/router/assets/47134711/b991bb26-7246-470f-afb0-6475cdd73923)

**Comment by gjtiquia** [comment]
![image](https://github.com/TanStack/router/assets/47134711/d5ed08fd-1dd9-480d-a78f-f2627a7cf23a)

Response from @tannerlinsley regarding this issue from Discord
https://discord.com/channels/719702312431386674/1198279811559333909 

Thanks @tannerlinsley and all the contributors!

**Comment by tannerlinsley** [comment]
Tracking this in #1048
