### ISSUE TITLE
Failed to reset error component properly

### ISSUE THREAD

**Issue by Zebeqo** [TanStack/router#1127]
### Describe the bug

I can't reset the error component neither through navigation nor through `router.load()`.

### Your Example Website or App

https://stackblitz.com/github/Zebeqo/tsr-reset-error-component

## case 1

1. Click on the link to `/a`
2. Click `Trigger error component` to display the error component of `/a`
3. Click the link to `/b` in the error component of `/a` displays the default error component when `/b` does not raise an error

## case 2

1. Click on the link to `/a`
2. Click `Trigger error component` to display the error component of `/a`
3. Clicking `router.load()` or the link to `/a` in the error component of `/a` still displays the error component.

### case 1

Show component of `b` when click the link to `/b` in the error component of `/a`.

### case 2

Shows component of `a` when click `router.load()` or the link to `/a` in the error component of `/a` 

### Platform

- OS: macOS
- Browser: Chrome
- Version: 120.0

**Comment by schiller-manuel** [comment]
is this still relevant with the latest version?

**Comment by Zebeqo** [comment]
> is this still relevant with the latest version?

Yes. Updated demo package version, verified in `1.18.1`.

**Comment by JorrinKievit** [comment]
Also experiencing this on 1.19.1

**Comment by jaens** [comment]
Still broken on the latest version. Using a link to navigate away from an error component does not work. (it actually does start working once you click a _second_ time on another link)

**Comment by TkDodo** [comment]
can confirm the issue, I think I'll have a fix for it up soon.

**Comment by jaens** [comment]
This is not fixed for our app in 1.22.9, still have to navigate twice to get away from error components in some cases (but I think something changed, since now *some* navigations work the first time...), and using the back button has the same problem.

**Comment by jaens** [comment]
[Here's a StackBlitz example:](https://stackblitz.com/edit/github-hwqxdl?file=src%2Froutes%2F_main%2Fa.%24param.tsx)

* navigate to `/a/n1`
* trigger error in `/a/n1`
* click on `/a/n2` - nothing happens
* click on `/b` - OK, this works
* re-trigger error in `/a/n1`
* click on `/b/` - now this is broken as well...

**Comment by jaens** [comment]
I can definitely still reproduce it in the larger app... `resetKey` changes, but the error component for some reason stays in place.

Is there a way to use a local version of Tanstack Router in another project? `CONTRIBUTING.md` unfortunately says nothing about that, and the monorepo + forced build step makes it hard to figure out how to actually do that.

**Comment by jaens** [comment]
I managed to workaround the `pnpm add` error by removing the `workspace:` dependency from the `packages/react-router/package.json`, although the DX is hell since either `pnpm` or Vite don't seem to be picking up any of the updated sources without repeatedly rebuilding and reinstalling a random amount of times.

**Comment by jaens** [comment]
The refresh hell is mostly due to Vite I guess, since it pre-bundles its dependencies and requires a server cache clear & browser cache clear to pick up any changes...

Anyway, I figured out part of the problem: The `resetKey` indeed changes, and the `CatchBoundary` tries to render its children again, but for some reason it's rendering the **old** children (ie. the old component that caused the error) instead of the component for the new route, so it just triggers it again.

**Comment by jaens** [comment]
Yeah, so what happens is that somewhere in the component tree, after a navigation from an error, a `Match` for the **old** route is somehow trying to render (but not mount) once, which triggers the error again.

Then the `Match` for the proper (new) route is rendered, but by that moment it is too late - the error has been caught by the root error component, and that sub-match is not going to be rendered since the `CatchBoundary` went into its error state.

**Comment by jaens** [comment]
Further digging down, the problem seems to be around  `getRenderedMatches`:

When navigating to a new route from an error, the proper route is already in the router's state `pendingMatches` field, but `getRenderedMatches` does not pick the pending match, but rather the old one from `matches` (well, related to `showPending` I suppose), which of course triggers the error again.

**Comment by TkDodo** [comment]
@jaens if you still have an issue, please file a new one with a minimal reproduction. Thanks.

**Comment by sbappuser** [comment]
@TkDodo Unfortunately, I tried making a minimal reproduction and it did not trigger the same issue, although the configuration for the router was I think exactly the same.

I was hoping that based on these details at least somebody could have a hint as to where the issue could be.

**Comment by marcinTichoniuk** [comment]
Also experiencing this on 1.45.6
