### ISSUE TITLE
The defaultPendingComponent is called twice on the first visit to the site.

### ISSUE THREAD

**Issue by qnpbgood** [TanStack/router#1360]
### Describe the bug

On the first visit to the site, the defaultPendingComponent is called twice for routes that have data fetching set up. The first time is as expected while the data is being loaded. The second time seems to be during the rendering of the component?

### Your Example Website or App

https://stackblitz.com/edit/github-nb92r2?file=src%2Frouter%2FpageB.ts

### Steps to Reproduce the Bug or Issue

1. Click to `pageB`
2. Reload the page to simulate the initial visit
3. Loader component triggered twice

### Expected behavior

Display the Loader component once

### Platform

- OS: Windows 11 Pro
- Browser: Chrome v123.0.6312.59

**Comment by SeanCassiere** [comment]
When you are using the `defaultPendingComponent`, it propagates this component to every route that needs a `pendingComponent`.

As such, when on `/pageB` and hit reload, the following sequence of events occurs.
1. Page loads, router is booting up. A pending component is shown.
2. The router completes the boot-up process and the root route and its children are rendered.
3. PageB is still "loading" because of its configuration, as such it needs a `pendingComponent` to be shown. This uses the `defaultPendingComponent`.

This isn't a bug, but rather the way the Router eagerly resolves its tree.

You could set the `pendingComponent` on the rootRoute, to have the fully page loading effect.

**Comment by rolftimmermans** [comment]
I'd like to add the following to this. While I appreciate that this is intentional, it seems it makes it impossible to create a single "global" pending component. This might seem like a minor issue, but if the pending component is animated, the animation will reset when it is re-rendered, causing a seemingly broken animation on first page load.

Adding a `pendingComponent` to the root route does not help because usually it's not the route loading data. 

Ideally there is a way for all suspense boundaries except the outermost one to be removed. I can remove all suspense boundaries in child routes (with a `wrapInSuspense: false` in every individual route) but on the root route this has no effect. Which leaves two suspense boundaries: one around the router and one around the root route. Which means the issue persists.

Any ideas how to tackle this are welcome, but in any case I thought I'd just provide this additional information why this can be a real issue.
