### ISSUE TITLE
When using hash history router reads and writes search params from fragment instead of query

### ISSUE THREAD

**Issue by owodunni** [TanStack/router#1449]
### Describe the bug

There is a discrepancy between `window.location.search` and the search parameters used
by the router when using hash routes. It seams that react-router is reading and writing search parameters in the hash fragment. Search parameters written in the normal query location are ignored.

URI  = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

According to he specification the query string should be before the hash fragment (rfc3986)[https://www.rfc-editor.org/rfc/rfc3986#section-3].

### Your Example Website or App

https://stackblitz.com/~/github.com/owodunni/router-test

### Steps to Reproduce the Bug or Issue

1. On the / page click the link `About with router search`, see that the component got the page search parameter. But `window.location.search` is empty.
2. On the / page click the link `About with 'normal' search`, see that the `window.location.search` is set.

### Expected behavior

As a developer I expect react-router websites to adhere to standard URI formats. It should be straight forward for me to communicate how others should link to my website with query parameters.

### Platform

- OS: any
- Browser: any
- Version: 1.26.16

### Additional context

The website I am developing uses query parameters outside of react-router to enable dev mode. This has to be set differently from other query parameters since its not for react-router to use.

**Comment by tannerlinsley** [comment]
I 100% agree with the RFC, which we adhere to in normal browser history routing mode, but I don't believe the RFC does or should apply to hash mode. Let me explain:

Hash mode exists to serve environments where normal paths and search params would otherwise break the distribution of the app, for example, running the router in an index.html file, or more historically, in browsers that didn't support the pushState API. Any normal navigation within these environments that involve changing the path or search params has strange effects, usually reloading or attempting to navigate to a non-existing file. This is why hash routing was invented, most notably more than a decade ago so that applications could utilize the only non-hard-reloading mechanism, hash updates, to change the state of a "virtual" URL on the page.

So in a way, the very idea of the hash router is already a departure from the RFC and the expected implementation of URLs. It's merely storing that RFC compliant URL inside of the hash. It's URL-ception!

Other reasons I don't think we should change anything here:

- Historical reasons. Many other frameworks and libraries work this way when in "hash" mode and it would be strange to change that.
- Breaking changes. This would be a breaking change for the whole library and any application + that apps bookmarks/shared-URLs/etc. This is not worth that churn.

**Comment by owodunni** [comment]
Thank you for taking the time to answer!
