### ISSUE TITLE
 Uncaught Error

### ISSUE THREAD

**Issue by andelkocvjetkovic** [TanStack/router#1513]
### Describe the bug

When an error is thrown within the loader, "Uncaught Error" appears in my browser console, even though the error page is shown.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-zz3epc?file=src%2Fposts.tsx

### Steps to Reproduce the Bug or Issue

1. Click on Post 1.
2. Open browser console and observe "Uncaught Error"
```
chunk-WM253HRZ.js?v=5f883516:1114 Uncaught Error at posts.tsx:15:20
```

### Expected behavior

I expect to the error within loader to be caught and clean console in my browser

### Screenshots or Videos

<img width="1440" alt="Screenshot 2024-04-24 at 11 25 34" src="https://github.com/TanStack/router/assets/56834937/6bd94ecd-301a-492e-bf72-67365f51898a">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 123.0.6312.124

**Comment by hugocostadev** [comment]
I'm having a similar error on the first load...

I have the index route that redirects to the `/home` route, but I'm having the error:

![image](https://github.com/TanStack/router/assets/20212776/fe5dc3e8-cc72-459a-bcce-ee390bac2761)

**Comment by andelkocvjetkovic** [comment]
I'm on `"@tanstack/react-router": "1.28.1"`, so I don't this it is related

**Comment by andelkocvjetkovic** [comment]
The issue is present in ` "@tanstack/react-router": "1.31.1"` as well

**Comment by SeanCassiere** [comment]
A couple of questions:

1. Just to be clear, the issue here is that we are logging the error to the console?
2. Why is logging the error to the console bad?

It's important to remember that this is client-sided, so there's no chance of **SECRETS** being revealed. Also, you'll only ever get here when there has been an error and the `errorComponent` has been triggered, and by default,`errors` are always printed to the console.

We'd need a valid reason to change this behaviour since some users have hooks that use the output of the console.

**Comment by andelkocvjetkovic** [comment]
My question is why I'm getting an 'Uncaught Error' in my console. Is this something I should take care of, and how precisely should I handle this? 

Thanks.

**Comment by SeanCassiere** [comment]
@andelkocvjetkovic this isn't something that requires intervention from you. No further error handling is required on your-part.

Very simply, the Error is printed out to the console since the application has encountered an error (intentional or not). You can choose to customize how you display the Error to the user using the `errorComponent`, but nevertheless an Error has occurred. As such, the error is printed to the console.

**Comment by lo1tuma** [comment]
I’ve just experienced the same issue and was quite confused that the error is printed as an uncaught error in the browser console because I’m explictly handling it as part of the `errorComponent`. Within the `errorComponent` I’m utilizing a custom error reporter (like sentry) to collect this error with additional context information. Usually uncaught errors are automatically collected as well. That mean I have the error reported twice, once explicitly via the `errorComponent` and once implicilty via the uncaught error that seemingly cannot be caught properly.
Is there any chance this behavior can be re-evaluated and maybe provide a way allow users of @tanstack/router to control how errors are handled?

**Comment by andelkocvjetkovic** [comment]
Yes, it is confusing. If a error is handled does it make sense to print it as uncaught ?

**Comment by bpinto** [comment]
I'm also getting duplicated errors reported as mentioned above. Since my error component is handling this error, IMO this isn't an uncaught error anymore.

IMO, if one is interested on logging it from within the `errorComponent` they could either `throw error` or `console.error(error)`.

**Comment by jameshoward** [comment]
This is definitely going to be a problem with global error handlers (such as Sentry) because they'll catch every loader error, even if we believe we've handled it gracefully. For example, an attempt to load a post with an ID that isn't valid. Even if we show a 'Post not found' error page to the user, this would still be logged to Sentry as an error.

**Comment by CanRau** [comment]
Same here, got very confused by those errors and would also prefer a "cleaner" approach, because I'd only expect those console errors if an unexpected and actually unhandled error happened, not when I'm prepared to have a normal 404 case basically

**Comment by jameshoward** [comment]
I dug into this some more today and realised it's an effect of how React and Error Boundaries work, rather than specific to Tanstack Router. Router is re-throwing the error (in `MatchInner` - https://github.com/TanStack/router/blob/main/packages/react-router/src/Match.tsx#L209) so it will get caught by the nearest `CatchBoundary` and it is this that renders your `errorComponent`. 

`CatchBoundary` is a React error boundary (has a `getDerivedStateFromError`) and React's default behaviour in dev is to render error boundaries and (kinda) re-throw the error (see https://github.com/facebook/react/issues/12897#issuecomment-410036991) and in a production build to `console.error` the caught error (see https://github.com/facebook/react/issues/15069)

I guess there's a reason to re-throw in `MatchInner` rather than rendering the `RouteErrorComponent` directly as it does if on the server?
