### ISSUE TITLE
Undefined context after redirect with wrapInSuspense at root route (introduced in 1.33.6)

### ISSUE THREAD

**Issue by Zebeqo** [TanStack/router#1650]
### Describe the bug

Undefined context after redirect with wrapInSuspense at root route.

It used to work fine in version 1.33.4.

### Your Example Website or App

https://stackblitz.com/edit/github-jr3nax-t75gmj?file=src%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

1. See the log: `context: undefined`
2. Remove `wrapInSuspense: true` and refresh
3. See the log: `context: {"test":"abc"}`

### Expected behavior

See the log: `context: {"test":"abc"}` at step 1

### Platform

- OS: macOS
- Browser: Chrome
- Version: 125.0

**Comment by Zebeqo** [comment]
> can you please check which version introduced this? 1.33.5 most likely did not since it affected @tanstack/start and not the router.

It's likely that the issue was introduced in version 1.33.6. I can confirm that version 1.33.4 was working fine, but the problem appears in version 1.33.6. As for version 1.33.5, it doesn't appear to be available on npm.

1.33.4: https://stackblitz.com/edit/github-jr3nax-xxb2ka?file=package.json
1.33.6: https://stackblitz.com/edit/github-jr3nax-uphkrn?file=package.json

**Comment by schiller-manuel** [comment]
then it is caused by this PR

https://github.com/TanStack/router/pull/1611

@SeanCassiere 
@freshgiammi

**Comment by freshgiammi** [comment]
Yeah, looks like this is working when my change is reverted, but I'm not sure reverting the change is the right fix. 
My patch merely fixes support for `wrapInSuspense` which got lost when some SSR changes were brought in (where the root route got forced to not suspend), so maybe this was broken before too. Seems we just keep bumping into ctx issues.

Reverting this change restores context after the redirect https://github.com/TanStack/router/commit/e19f7e8703bdc8d6ccbaf3399c82527aabdc56c2#diff-2ac234f610fa0e0c2146252c10a5266af9c5b6d0b63659a0fa4c9f2c4472596a

I wonder if the root cause lays elsewhere 🤔
