### ISSUE TITLE
The test does not work when rendering the router

### ISSUE THREAD

**Issue by dmitriybo** [TanStack/router#1654]
### Describe the bug

```ts
import {
  createRootRoute,
  createRouter,
  RouterProvider,
} from "@tanstack/react-router";
import { render, act } from "@testing-library/react";
import { test } from "vitest";

test("router", async () => {
  const router = createRouter({ routeTree: createRootRoute() });
  act(() => render(<RouterProvider router={router} />));
});
```

An error occurs when running the test
```
Warning: An update to Transitioner inside a test was not wrapped in act(...).

When testing, code that causes React state updates should be wrapped into act(...):

act(() => {
  /* fire events that update state */
});
/* assert on the output */
```
How to properly test a router?

### Your Example Website or App

https://codesandbox.io/p/devbox/magical-joana-mmtmlc?file=%2Ftest.test.tsx%3A13%2C1

### Steps to Reproduce the Bug or Issue

1. Go to https://codesandbox.io/p/devbox/magical-joana-mmtmlc?file=%2Ftest.test.tsx%3A13%2C1
2. Run command `yarn test` (most likely you need to make a fork)

### Expected behavior

No warning will occur

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by samgqroberts** [comment]
I'm seeing this as well after attempting an upgrade from 1.26.20 (where it worked fine) to 1.34.4 (where this log began happening many times per test). This is an issue when running [testing-library](https://testing-library.com/)-backed tests with the newer versions of TS router.

The versions I'm using are:
```
    "@tanstack/react-router": "^1.34.5",
    "@testing-library/jest-dom": "6.4.5",
    "@testing-library/react": "14.3.1",
    "vitest": "1.6.0"
```

I would really like to continue testing TS Router-based applications from the RouterProvider level using testing-library.

**Comment by samgqroberts** [comment]
I tried a the reproduction on several versions and found the following:

In **v1.28.1** the act(...) warnings are NOT there. This is likely the version I will pin my projects to until we make headway on this issue.

In **v1.28.2** my tests that render a RouterProvider throw errors with messages:
```
Error: Uncaught [Error: A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.]
...
The above error occurred in the <MatchInner> component
``` 

In **v1.28.3** that error ^ is gone, but the act(...) warnings are back, and it seems like they stay back all the way through the current version (1.34.5 as of this comment).

**Comment by samgqroberts** [comment]
Okay I believe I've found a solution here. It doesn't look like there's anything wrong with TS Router, it just looks like we have to treat initial testing-library rendering of RouterProvider differently as of the introduction of Suspense here: https://github.com/TanStack/router/commit/713f92de7ff9eb21182cb510692a621e5df8b3c0. Basically we have to make sure that the initial render result has a chance to compute some number of asynchronous ticks underneath an `act`.

So for example, whereas previously in v1.28.1, the following test would not cause any issues:
```
  test('rendering the router via testing-library', async () => {
    const result = render(<RouterProvider router={router} />);
  }|
```

In 1.28.3 we would see the act() warnings because the test ends while Suspense still has outstanding promises, just like would happen in any testing-library test case with outstanding promises that would thereafter affect React state.

I have found that this issue is avoided by just waiting for TS Router to do _anything_ initially. The following improvement to the repro test case above now does not produce any act() warnings for me on either 1.28.3 nor 1.34.5:
```
  test('rendering the router via testing-library', async () => {
    const result = render(<RouterProvider router={router} />);
    await waitFor(() => result.baseElement.childNodes[0]!.hasChildNodes());
  });
```

The logic behind that waitFor is: when testing-library initially renders RouterProvider, all we have in the result is:
```
<body>
  <div />
</body>
```

That `<div />` is the mount point where all children of the router provider will go. So the `waitFor` is waiting for the mount point to be populated by anything, which it seems means that the Suspense has gotten through its loading state.

**Comment by schiller-manuel** [comment]
can we close this issue?

**Comment by samgqroberts** [comment]
I'm fairly satisfied with the investigation and I'm not seeing these warnings in my project after adopting the `await`. I'm pretty confident the investigation / solution is generalizable, so in my opinion we can close this issue.

**Comment by dmitriybo** [comment]
Thanks everyone, I corrected all the tests, everything works
