### ISSUE TITLE
File base subroutes regression

### ISSUE THREAD

**Issue by matt-erhart** [TanStack/router#1655]
### Describe the bug

File based subroutes no longer matched in newest version, but are matched in "1.32.8". I went back in time in the release notes to roughly when I was sure things were working. Edit: now no versions are working, will need to mess with vite plugin versions.

### Your Example Website or App

https://stackblitz.com/edit/github-1eblyy-7zzpaw?file=src%2Froutes%2Fabout.subroute.index.tsx

### Steps to Reproduce the Bug or Issue

1. Take a basic example and delete all the routes except __root.tsx and index.tsx. I did basic-file-based.
2. create a one level route, eg testroute.tsx, works as expected
3. create a file with a subroute in it, eg testroute.subroute.tsx or testroute.subroute.index.tsx.

### Expected behavior

when linked to testroute/subroute, it should show the content of testroute.subroute. 

### Platform

- OS: [Windows]
- Browser: [Chrome, Edge]
- Version: [1.33.7] (at least)

### Additional context

I swear I saw it work properly and then not work, perhaps something to do with the vite plugin. Is this a major bug or am I doing something wrong?

**Comment by matt-erhart** [comment]
Folder based routes appear to be working.

**Comment by schiller-manuel** [comment]
You are missing an `<Outlet />`:

```tsx
function AboutComponent() {
  return (
    <div className="p-2">
      <h3>About</h3>
      <Outlet />
    </div>
  );
}
```

see https://stackblitz.com/edit/github-1eblyy-wubjtc?file=src%2Froutes%2Fabout.tsx

without the `<Outlet />`, rendering stops at the `about` route.

**Comment by schiller-manuel** [comment]
> Folder based routes don't need an outlet for nested routes, but file based ones do

no, all routes need outlets in order to let child matches render.
however, typically when you define folder based routes like this:

```
foo/
   bar.tsx
```

Then you don't define the `foo` route explicitly and hence you also do not define the component that is being rendered for `foo`.
If a component is not specified, it defaults to just `<Outlet />`.

You could also define a file route like this, omit the component and then router will use an outlet for this:
```tsx
export const Route = createFileRoute('/about')({
});
```

And, you can also explicitly define the folder based route either like this:

```
foo/
   bar.tsx
foo.tsx
```

or this:

```
foo/
   bar.tsx
   route.tsx
```

in either case, if `foo.tsx` or `route.tsx` specify a component, this needs to contain an outlet.
