### ISSUE TITLE
Incorrect not found component being rendered

### ISSUE THREAD

**Issue by mrlubos** [TanStack/router#1657]
### Describe the bug

Hey, I am trying to implement a notFoundComponent. During testing, I am getting this warning in console

```sh
Warning: A notFoundError was encountered on the route with ID "/_foo/_bar/foo/$foo", but a notFoundComponent option was not configured, nor was a router level defaultNotFoundComponent configured. Consider configuring at least one of these to avoid TanStack Router's overly generic defaultNotFoundComponent (<div>Not Found<div>)
```

The documentation says

>By default, the router's notFoundMode is set to fuzzy, which indicates that if a pathname doesn't match any known route, the router will attempt to use the closest matching route with children/(an outlet) **and a configured not found component**.

Notice the emphasis (mine) on the closest match with outlet and a configured not found component. My understanding is that if either of these conditions is not met, the router will keep climbing up the route tree and display the first parent that meets both criteria. That is not what I am seeing, unless I am doing something wrong.

### Your Example Website or App

https://stackblitz.com/edit/github-gernwd?file=src%2Froutes%2F__root.tsx,src%2Froutes%2F_foo._bar.tsx,src%2Froutes%2F_foo._bar.foo.%24foo.bar.tsx

### Steps to Reproduce the Bug or Issue

1. Observe I have two layout routes (`_foo` and `_foo._bar`) and two app routes (`/foo/:foo` and `/foo/:foo/bar`)
2. In `__root.tsx`, I define a non-existent path (`/foo/:foo/not-found`) that should show the correct 404 error if visited (defined in `_foo._bar.tsx`).
3. Click on "Not Found Route" link in main page navigation
4. Observe an incorrect not found component is rendered

### Expected behavior

Assuming this is my route structure:

`_foo.tsx` > `_foo._bar.tsx` > `_foo._bar.foo.$foo.tsx` > `_foo._bar.foo.$foo.bar.tsx`

I want to catch any non-existent routes in `_foo._bar.tsx`. Therefore, `notFoundComponent` component defined in `_foo._bar.tsx` should render. If I rename or remove `_foo._bar.foo.$foo.bar.tsx`, that is indeed what happens. However, I cannot do that, because my application needs to match and render `/foo/:foo/bar` when navigated to it. What's happening?

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SeanCassiere** [comment]
Since you are using pathless/layout routes, navigating to `/foo/random-param/not-found` wouldn't ever actually match the layout routes above it.

Pathless/layout routes are more fine-grained and require more precision. Creating a wildcard route under your layout route and triggering the layout route's not-found boundary would be the way to go here.

```tsx
// src/routes/_foo._bar.$foo.$.tsx
import { createFileRoute, redirect } from '@tanstack/react-router'

export const Route = createFileRoute('/_foo/_bar/foo/$foo/$')({
  loader: () => {
    throw redirect({ routeId: '/_foo/_bar' })
  }
})
```

**Comment by mrlubos** [comment]
Thanks @SeanCassiere, I was sure it's something missing on my part. Are you able to explain why renaming/removing that one route produces the expected result?

**Comment by SeanCassiere** [comment]
Its to do with how route matching works.

When pathless/layout routes are being used, you need all the route segments to be present for it to match correctly to the layout routes. Earlier, when you were going to that wildcard/not-found route, it didn't match with any of the parents, because TSR wasn't told that a wildcard route could exist for that layout route scenario.

By adding in that wildcard route you are telling TSR that there's a possibility for a wildcard to exist, and as that wildcard route is visited to, then the router should know what the route's parents are. Once that's done, its then just the normal route matching at work.
