### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by hckhanh** [TanStack/router#1686]
### Describe the bug

I access my route with this url: `http://localhost:3000/login?redirect=http:/%localhost:3000/standalone/policies-new/15MRZKHBCC/CAR_COMPREHENSIVE`

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

1. Define a normal route

### Expected behavior

It should not throw any internal bugs

### Screenshots or Videos

![image](https://github.com/TanStack/router/assets/6380436/72e19998-7d4d-436b-b3fc-794dd50651f8)

![image](https://github.com/TanStack/router/assets/6380436/05671536-b9ec-44ba-8100-d61ea4dbc843)

### Platform

- OS: Windows
- Browser: Chrome
- Version: 125.0.6422.113

**Comment by schiller-manuel** [comment]
decoding `http:/%localhost:3000/standalone/policies-new/15MRZKHBCC/CAR_COMPREHENSIVE` with `decodeURIComponent` yields this error, so not a router problem:

![Screenshot 2024-06-03 at 19 02 52](https://github.com/TanStack/router/assets/6340397/16b7df9c-3eac-46cc-89bc-018fe23edfaf)

Looks like you got a `%` instead of a `/` in your search param and thus its not correctly encoded.

**Comment by hckhanh** [comment]
I mean if someone intend to make this error. How can I prevent this. My Sentry service just make an alarm about this all the time.

**Comment by hckhanh** [comment]
I hate the way you close the issue like this before you can clearly understand the context.

**Comment by schiller-manuel** [comment]
please provide all the necessary context in the issue description in future

**Comment by schiller-manuel** [comment]
what would you expect to happen when you pass a wrongly encoded query string?
