### ISSUE TITLE
Router and createRouter has different behavior

### ISSUE THREAD

**Issue by ssjunior** [TanStack/router#1722]
### Describe the bug

the Router class is deprecated and will be removed in the next major version of TanStack Router. Please use the [createRouter](https://tanstack.com/router/latest/docs/framework/react/api/router/createRouterFunction) function instead.

Everything is running fine with Router class, but, if I try to use createRouter as per instructed an error happens.

Working:

return new Router({ routeTree: rootRoute })

not working:

return createRouter({ routeTree: rootRoute })

the error is: 

```
Uncaught 
TypeError: currentMatches is not iterable
    at RouterProvider (@tanstack_router.js?v=513a5a29:715:24)
    at renderWithHooks (chunk-UHJUCBBD.js?v=2b41ed85:11568:26)
    at mountIndeterminateComponent (chunk-UHJUCBBD.js?v=2b41ed85:14946:21)
    at beginWork (chunk-UHJUCBBD.js?v=2b41ed85:15934:22)
    at HTMLUnknownElement.callCallback2 (chunk-UHJUCBBD.js?v=2b41ed85:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-UHJUCBBD.js?v=2b41ed85:3699:24)
    at invokeGuardedCallback (chunk-UHJUCBBD.js?v=2b41ed85:3733:39)
    at beginWork$1 (chunk-UHJUCBBD.js?v=2b41ed85:19793:15)
    at performUnitOfWork (chunk-UHJUCBBD.js?v=2b41ed85:19226:20)
    at workLoopSync (chunk-UHJUCBBD.js?v=2b41ed85:19165:13)
```

### Your Example Website or App

no website or app

### Steps to Reproduce the Bug or Issue

1 - Create a rootRoute
2 - Create a router using Router
3 - Create a router using createRouter

### Expected behavior

I expect to both have the same behavior in both situations.

### Platform

macOs
react 18.3.1

**Comment by SeanCassiere** [comment]
When you are creating the router instance with the  `routeTree`, it first needs to turned to its children format as such:

```tsx
import { createRouter, Router } from '@tanstack/react-router'
import { rootRoute } from './routes/__root.tsx'

const routeTree = rootRoute.addChildren([
  // other routes
])

const classRouter = new Router({ routeTree })

const functionRoute = createRouter({ routeTree })
```

There is no implementation difference, since `createRouter` just instantiates the `Router` class under the hood. You can see the implementation for yourself [here](https://github.com/TanStack/router/blob/6979e62d036041121484201849fbecaaf4c70c5e/packages/react-router/src/router.ts#L456-L475).

@ssjunior if you have a valid reproduction of this, please do provide a minimal reproducible example.

You can create such a reproduction using either the [Router file-based stackblitz starter](https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart-file-based) or the [Router code-based stackblitz starter](https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart).
