### ISSUE TITLE
Route.update() does not update state options.

### ISSUE THREAD

**Issue by itshallrun** [TanStack/router#1868]
### Describe the bug

Using Route.update() does not update options in state, especially staticData.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-bjnyvy?file=src%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

1.  go to [reproduction](https://stackblitz.com/edit/tanstack-router-bjnyvy?file=src%2Froutes%2F__root.tsx) example
2. create a route or check the existing root route
3. trigger a Route.update({staticData: {someStaticValue: "updated value"})
4. The returned object from Root.update() does have the updated options
5. The state in the tanstack router devtools, or when retrieved by useMatches or else, does not have the updated options

### Expected behavior

The state should update reactively.
All components depending on the state (components with useMatches and so on) should rerender and show the updated state options.

### Screenshots or Videos

![image](https://github.com/TanStack/router/assets/21173275/bcc746e8-9202-4d4a-b8d6-a866f15c116e)

### Platform

- OS:macOS
- Browser: Chrome
- Version: 126.0.6478.63

**Comment by SeanCassiere** [comment]
From what I understand the `staticData` wasn't ever meant to be reactive. As mentioned in the [static route data guide](https://tanstack.com/router/latest/docs/framework/react/guide/static-route-data), it is meant to be set when you initially create/define a route. 

Also, the `Route.update` method is only used for updating route definition details and has no expectations of reactivity since these are changes made that the internals track, like staleTime, gcTime, component imports, etc... In user-land, there's no expectation of reactivity here, since the only actual reactive elements have been exposed via their typed hooks (`Route.useRouteContext()`, `Route.useSearch()`, `Route.useParams()`, `Route.useLoaderData()`, `Route.useLoaderDeps`, and `Route.useMatch()`).

**Comment by itshallrun** [comment]
@SeanCassiere thank you for your response. 

So staticData is not reactive, that makes sense now.
However, I really struggle with setting up dynamic Breadcrumbs.
I want to fetch some Data from within the component, and then use it in the Breadcrumbs.
Seems like routeContext is a perfect match here, but I don't see a way to reactively update it from within the component either? Is there a way?

**Comment by SeanCassiere** [comment]
Typically, we'd suggest using `routeContext` through the `beforeLoad` callback, but this never receives the `loaderData` (and the loader is at the bottom in the order of execution).

I'd at this point reach for an external state manager or something more custom.

**Comment by itshallrun** [comment]
@SeanCassiere thank you for the answer.

Could you please let me know if it’s possible to set the routeContext directly within the component, without using the loader? I would like to avoid it in my special case.

**Comment by SeanCassiere** [comment]
> Could you please let me know if it’s possible to set the routeContext directly within the component, without using the loader? I would like to avoid it in my special case.

Route context can be set only:

- During router initialization
- From the `beforeLoad` callback of the current route.
- From the `beforeLoad` callback of the parent route.
