### ISSUE TITLE
<Body /> component ignores attributes as props

### ISSUE THREAD

**Issue by glocore** [TanStack/router#1915]
### Describe the bug

[TanStack Start]

Adding HTML attributes as props doesn't seem to work with the `<Body/>` component. Typescript typings suggest that it accepts all HTML attributes as props.

Tried it with the [Stackblitz example app](https://stackblitz.com/github/tanstack/router/tree/main/examples/react/start-basic-counter) from the docs:

```tsx
<Body style={{ backgroundColor: "black" }}>
  {children}
  <ScrollRestoration />
  <Scripts />
</Body>
```

The style attribute doesn't get applied. Works fine if I use a regular `<body/>` element.

### Your Example Website or App

https://stackblitz.com/github/tanstack/router/tree/main/examples/react/start-basic-counter

### Steps to Reproduce the Bug or Issue

1. Open the [Stackblitz example](https://stackblitz.com/github/tanstack/router/tree/main/examples/react/start-basic-counter) from the docs.
2. Add any HTML attribute to the `<Body/>` component.
3. The attributes are not applied to the underlying `<body>` element.

### Expected behavior

The HTML attributes should get applied? Unless I mis-understood the purpose of the `<Body/>`, `<Html/>`, etc. components.

### Platform

- OS: macOS
- Browser: Chrome
- Version: @tanstack/start v1.43.2

**Comment by SeanCassiere** [comment]
This is [intentional](https://github.com/TanStack/router/blob/08d3e61b4c9652d37a6685f37e8d366762b2633e/packages/start/src/client/Meta.tsx#L231-L234).

This'll become available once React 19 drops.

For now, I'd recommend using a stylesheet using  imported using `links` or to simply render a style tag. Both of which would target the body element.
