### ISSUE TITLE
validateSearch called when hovering unrelated routes on Links

### ISSUE THREAD

**Issue by alemagvs** [TanStack/router#1919]
### Describe the bug

I was investigating performance issues in my own project where i have a table with a 300~ Links that had performance issues and when I added a console.log in the validateSearch of the current route it printed for every Link I created. I then managed to somewhat reproduce this in the Kitchen Sink example. 
I'm not sure if the performance issue is related, but it seems unperformant to call validateSearch for Links that do not match the path.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-zzmuer?file=src%2Froutes%2Flogin.tsx

### Steps to Reproduce the Bug or Issue

Go to:

https://stackblitz.com/edit/tanstack-router-zzmuer?file=src%2Froutes%2Flogin.tsx

Here I've just changed validateSeach to

`validateSearch: (search) => {
    console.log('validating login', Math.random());

    return z
      .object({
        redirect: z.string().optional(),
      })
      .parse(search);
  }`

Hovering any Link pointing to users/invoices/other routes will call the login validateSearch, multiple times.

### Expected behavior

Only call validateSearch on Links with a "to" matching "/login", or similar.

### Screenshots or Videos

https://github.com/TanStack/router/assets/87984222/c041b1e7-5070-4d43-9f58-7bb08b49fb88

### Platform

Linux, ubuntu 22
Firefox/Chrome, latest

**Comment by SeanCassiere** [comment]
The `validateSearch` option gets called [here](https://github.com/TanStack/router/blob/4cd80bb4948df638fa7739764d8d85c46ac113b4/packages/react-router/src/router.ts#L991-L996) in `router.matchRoutes` for all the matches.

Looking into this for this scenario, the `validateSearch` call gets called in these instances (as far as I can tell):
- During the instantiation of the `<Link>` component.
- When hovering a link (aka preloading). 
- When using a `matchRoute` call.

This is because at each of these places we either end up calling `router.buildLocation` (which internally calls `router.matchRoutes`) or directly call `router.matchRoutes`. These calls end up calling `validateSearch` option on each of the matches internally.

This issue is also related to #1481 where `validateSearch` gets called on other routes.

I'll investigate what's the effect of running the `validateSearch` only `onLoad`.

**Comment by SeanCassiere** [comment]
This would definitely require consideration since making changes to this behaviour affects how route preloading works.

For the time being, I don't think we can alter this behaviour since the router depends on the search params being validated in the `router.matchRoutes` method (as mentioned [here](https://github.com/TanStack/router/blob/78c27801b9666712cb7786c8939a2a27b83646b2/packages/react-router/src/router.ts#L977-L982)) for it to create the actual route matches used downstream.

Going to have to leave this for the time being.

**Comment by SeanCassiere** [comment]
I'm closing this since the router relies on the validateSearch function being called to validate the URLs being generated for use in the `<Link>` component. Also, since this issue, being made performance improvements to memorize all the routes internally as well as further refinements into how the `<Link>` component's props are handled.
