### ISSUE TITLE
`route.id` and `getRouteApi` work inconsistently for routes with pathless parents

### ISSUE THREAD

**Issue by bohdancho** [TanStack/router#2130]
### Describe the bug

If a route is a child of a pathless route, the pathless segment of it's path is included in its `route.id`. This makes it impossible to pass it as the `to` prop to `<Navigate>` or `<Link>`. Moreover, 'getRouteApi` also requires passing the full path, including the pathless segment.

### Your Example Website or App

https://stackblitz.com/edit/github-puypjk-egbfth?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Open the example link
2. See that `<Link>`, `<Navigate>` and `getRouteApi` error

### Expected behavior

I expected to be able to
1. pass `route.id` to as `to` prop to `<Navigate>` and `<Link>` just like with routes without pathless parents
2. not have to specify the pathless segment of a route in `getRouteApi`

### Platform

- OS: Windows
- Browser: Chrome
- Version 127.0.6533.119 (Official Build) (64-bit)

**Comment by SeanCassiere** [comment]
- `Route.id` is not a valid navigation `to` option.
  - `Route.fullPath` is what'd you'd want to use when setting it on `<Link>` and `navigate`.

- The string literal parameter accepted by the `getRouteApi` helper, expects the `routeId` to be its input. See [docs](https://tanstack.com/router/latest/docs/framework/react/api/router/getRouteApiFunction).
  - Since it requires a valid `routeId` to be its input, the pathless/layout route segments do comprise that string.
  - If you've got the `router-devtools`, you can open the panel and confirm the `routeId`'s value at runtime by viewing it in the tree.

**Comment by bohdancho** [comment]
Thanks a lot! I also noticed the `Route.to` field. Using it instead of `Route.fullPath` seems to result in the same outcome. Could you please clarify the difference and how to know which one of the two should be used?

**Comment by SeanCassiere** [comment]
> Thanks a lot! I also noticed the `Route.to` field. Using it instead of `Route.fullPath` seems to result in the same outcome. Could you please clarify the difference and how to know which one of the two should be used?

ATM I don't quite remember why we introduced both. We've always pushed people to use `Route.fullPath`, so I'd stick with that for now.

If bundle size is a concern at all, I'd not go out of my way to import external `Route` configs into a file, and just stick with the `string` literals instead. Plus, you sometimes run the risk of having circular imports.
