### ISSUE TITLE
`useMatches().reverse()` causes the layout to render incorrectly only after the build, not during development mode.

### ISSUE THREAD

**Issue by kimwonj77** [TanStack/router#2254]
### Which project does this relate to?

Router

### Describe the bug

It is partly my fault, as I didn't notice this until I was about to do a `build` and upload it to S3.

Using `const matches = useMatches(); matches.reverse()` works well in `dev` (HMR) mode and renders all layouts without errors. However, after a static build, this approach fails, displaying only the last route without any nested routes.

This seems unintended, but it remains an issue due to the differing behavior between HMR and static builds.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-mjpm9h?file=src%2FMatchesComponent.tsx

### Steps to Reproduce the Bug or Issue

1. Use `useMatches()`.
2. Reverse the matches with `matches.reverse()`.
3. Run `vite build` and `vite preview`—`vite` works fine, but the issue arises after the static build.

### Expected behavior

Similar to a dev build, this should render as a nested layout.

### Dev

![Image](https://github.com/user-attachments/assets/3dd5e20e-cd91-4804-9b73-f7860ba64e19)

### Build - preview

![Image](https://github.com/user-attachments/assets/42039bb8-47fe-48c3-9aa0-2af76376843b)

### Platform

- OS: [Windows, macOS]
- Browser: Chrome
- Version: 128.x

### Additional context

Using `const newMatches = [...matches]; newMatches.reverse()` works as expected in both modes as a workaround.

**Comment by SeanCassiere** [comment]
You need to be spreading the matches and then calling `.reverse()`. This is because `.reverse()` is one of those older javascript methods on the Array prototype that mutates the existing reference instead of _copying_ it and returning a new reference (like with `.map` or `.reduce`).

See the official MDN documentation on `Array.prototype.reverse()` - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse
