### ISSUE TITLE
[TanStack Router]: Production version/builded version fails to resolve any other route than / (v1.70.0)

### ISSUE THREAD

**Issue by JosueGalRe** [TanStack/router#2560]
### Which project does this relate to?

Router

### Describe the bug

Hi! Thanks for such an amazing library!

I'm having this issue where the build version can't resolve any route but `/`. I haven't able to find a solution for this, and it also happens on the kitchen-sink-file-route demo

### Your Example Website or App

https://github.com/TanStack/router/tree/main/examples/react/kitchen-sink-react-query-file-based

### Steps to Reproduce the Bug or Issue

1. Clone/Download demo
2. Enter folder
4. Install dependencies `pnpm install`
5. Build project `pnpm build`
6. Install serve (or any other http server, I have tested it on serve) `pnpm install -g serve`
7. Serve dist `serve ./dist`
8. Go to `localhost:3000`
9. Go to any page other than root  `/` using page links, i.e: `/login`
10. Reload
11. Expect a 404 error

### Expected behavior

I would expect that all routes are resolved correctly regardless if the URL is root `/` or not

### Screenshots or Videos

https://github.com/user-attachments/assets/be094d92-cd48-44fc-a626-089960e34cc4

### Platform

- OS: Tested on Linux, Windows, MacOS
- Browser: Edge, Zen, Vidaldi
- Version: 1.66.1, 1.70.0

### Additional context

Tested using `{ autoCodeSplitting: true }` in `tsr.config.json` and using combination of normal routes and lazy routes

**Comment by SeanCassiere** [comment]
All SPA (Single Page Applications) have a single entry point, the `index.html` file. The reason why navigation works when you first go to `http://localhost:3000` is because it first loads the `index.html` entry file which in-turn loads in the necessary javascript. Once loaded in, the javascript hijacks the navigation to ensure all navigation events happen whilst still remaining on the same entry point.

The reason why it doesn't work when using `serve` is because it treats the contents of your `dist/` folder as if it were a server. As such, when you visit `http://localhost:3000/login`, it tries to resolve to an entry point named `login.html` which does not exist. The solution here is to use the `index.html` file as the handler for all 'unresolved' entries. This is also, what you'd have to do when deploying to a platform like Vercel or Netlify.

This behaviour is the same across Remix's React Router and Wouter.

---

For your situation, you can use vite's built in command that handles this resolution automatically without additional configuration.

```sh
vite preview --port 3000
```

https://vite.dev/config/preview-options
