### ISSUE TITLE
createServerFn not propagating error

### ISSUE THREAD

**Issue by hahnrobert** [TanStack/router#2577]
### Which project does this relate to?

Start

### Describe the bug

```
export const some_fn = createServerFn("POST", async (_) => {
  throw new Error("always throw");
});

const mutation = useMutation({
        mutationFn: some_fn,
        onError: (error) => {
            console.log(error)
        }
})

<button onClick={() => mutation.mutate()}>click me</button>
```

The POST request returns a 200 and no error is returned in the network request or logged by the client in any other way.

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

See code above

### Expected behavior

The onError function is called accordingly.

### Platform

- OS: macOS
- Browser: Chrome
- Version:
```
    "@tanstack/eslint-plugin-query": "^5.59.7",
    "@tanstack/react-form": "^0.34.0",
    "@tanstack/react-query": "^5.59.15",
    "@tanstack/react-query-devtools": "^5.59.15",
    "@tanstack/react-router": "^1.33.2",
    "@tanstack/react-router-with-query": "^1.70.1",
    "@tanstack/router-devtools": "^1.33.2",
    "@tanstack/router-vite-plugin": "^1.32.17",
    "@tanstack/router-zod-adapter": "^1.70.1",
    "@tanstack/start": "^1.70.0",
    "@tanstack/zod-form-adapter": "^0.34.0",
```

**Comment by schiller-manuel** [comment]
the error not being returned is already tracked here: https://github.com/TanStack/router/issues/2535

**Comment by np-13** [comment]
> the error not being returned is already tracked here: [#2535](https://github.com/TanStack/router/issues/2535)

I believe that is a different issue, though. #2535 concerns error serialization, whereas this one concerns the error never being caught client-side since the status code is 200 (used to be 500 by default before [this](https://github.com/TanStack/router/pull/2553/files#diff-7a74f9a15c12fb0a215372ce2a689b49a789ce04c0917a9ad4d7d5364911bf16R158) change). As it stands right now, there is no way to determine if the function failed because there is no way to read Server Function response headers.

One way to catch the error right now is to wrap the server function body into an additional try-catch, which changes the response status code in `catch`:

```typescript
import { setResponseStatus } from 'vinxi/http';

function doStuff() {
  throw new Error('It failed');
}

const doStuffFn = createServerFn('POST', async () => {
  try {
    return doStuff();
  } catch (e) {
    setResponseStatus(500);
    throw e;
  }
});
```

If we put the serialization issue aside, functions that throw an error should not return status code 200 when the user code does not handle the error explicitly.
