### ISSUE TITLE
[Feature Request] Only consider directories that contains index.tsx

### ISSUE THREAD

**Issue by cathaysia** [TanStack/router#2688]
In nextjs app router, it only contains directories that contains a page.tsx file:

https://nextjs.org/docs/app/building-your-application/routing#roles-of-folders-and-files
> Folders are used to define routes. A route is a single path of nested folders, following the file-system hierarchy from the root folder down to a final leaf folder that includes a page.js file. See [Defining Routes](https://nextjs.org/docs/app/building-your-application/routing/defining-routes).

Currently, @tanstack/router allow ignore file/directory by `routeFileIgnorePrefix`, or `routeFileIgnorePattern`. But it force me to add some prefix on files. It would be nice if @tanstack/router could have similar behavior to nextjs.

**Comment by schiller-manuel** [comment]
you don't need an index if you have no other routes (e.g. a`$id`)
so we cannot implement this really.
unless I misunderstood this. can you please provide a complete minimal example and show which files/folders should be ignored?

**Comment by cathaysia** [comment]
I have a tsr.confg.json like this:

```json
{
  "routesDirectory": "src/app",
  "indexToken": "page",
  "routeToken": "layout",
  "autoCodeSplitting": true,
  "semicolons": true,
  "routeFileIgnorePrefix": "!"
}
```

And then my project's structure is:

![Image](https://github.com/user-attachments/assets/29d5651c-5ae7-4069-9d3a-a78307b7ed7e)

I want ignore the components directory.

**Comment by schiller-manuel** [comment]
@SeanCassiere is absolutely right.

you can also just move the component directory out of the routes directory. 

so lots of possibilities exist already, no need to add further complexity

**Comment by cathaysia** [comment]
Yes, there are two reasons why I prefer the nextjs approach:
1. Nextjs is the first router I learned
2. Flat naming does not look very beautiful.

Although it is a bit disappointing, it is acceptable after all

**Comment by SeanCassiere** [comment]
Both of these are something we hear often enough.

> Nextjs is the first router I learned.

In our opinion, Next's routing whilst simple is quite limiting.

> Flat naming does not look very beautiful.

The flat-naming is something we've come to love since it allows you to pretty easily understand the URL without having to trace it back through your file explorer.

---

I've got a project combining the "flat-routing" with "route grouping" as well as the `"-components"` naming structure. Take a look at it you may find some value in its setup.

https://github.com/SeanCassiere/nv-rental-clone/tree/master/src/routes/_auth/(customers)
