### ISSUE TITLE
Getting started guide for Start missing import

### ISSUE THREAD

**Issue by RobinClowers** [TanStack/router#2793]
### Which project does this relate to?

Router

### Describe the bug

When following the [Getting Started](https://tanstack.com/router/latest/docs/framework/react/start/getting-started) guide, I get this error when I try to run load my app:

```
Error in renderToPipeableStream: ReferenceError: React is not defined
    at Home (/Users/robin/src/tanstack-start-demo/app/routes/index.tsx?tsr-split:31:3)
```

Adding a react import in `__root.tsx` and the `index.tsx` route fixes it, which makes it seem like Start doesn't use the newer automatic JSX runtime? In any case, if the explicit imports are required, they should be included in the examples.

### Your Example Website or App

https://github.com/RobinClowers/photo-album-tanstack/tree/tanstack-getting-started-bug

### Steps to Reproduce the Bug or Issue

1. Create a new vite react app `pnpm create vite` and select react.
2. Delete the vite config, index file and main.tsx.
3. Follow the getting started guide from [Install Dependencies](https://tanstack.com/router/latest/docs/framework/react/start/getting-started#install-dependencies).
4. Visit localhost:3000 and observe the error in the dev server output.

### Expected behavior

I expected the page to render without an error.

### Platform

- OS: macOS
- Browser: Firefix
- Version: 132

**Comment by SeanCassiere** [comment]
Could you try this again without using `pnpm create vite`? The deps being installed using the vite app creation could be creating conflicts.

**Comment by RobinClowers** [comment]
Apologies, this is because the `create vite app` assumes an `src` directory, rather than `app`, which I didn't notice. This works fine if "app" is the `tsconfig.app.js` `include` option.

**Comment by luixo** [comment]
I've got the same problem.
I'm trying to migrate a pet project from Next.js to TanStack Start and got this error, though only in SSR.
In my case adding `import React from 'react'` doesn't help though.

Client works ok (ignoring all the errors of hydration mismatch - as server renders error instead of the actual markup), no problems of importing `React`.

Can I debug code transformation that happens SSR / CSR to see where the underlying difference is?

I noticed vite react plugin is only [imported](https://github.com/TanStack/router/blob/2088be2a2a85fed205c5040751a6ed1571e10072/packages/start/src/config/index.ts#L176) in client section, how is server expected to get `React` auto-imported?

**Comment by jkbmat** [comment]
@luixo did you manage to fix the issue in the end?

**Comment by luixo** [comment]
Not really, currently I gave up on spinning up Tanstack Start :(

**Comment by Brammm** [comment]
I got this error today as well after installing tanstack/router in an existing bare React project. When I had set up the project, @vitejs/plugin-react wasn't installed yet. By installing and configuring that, the problem was fixed.

**Comment by studiopachinko** [comment]
> @vitejs/plugin-react

Had the same issue, installing @vite/plugin-react and adding to vite.config.ts as per https://www.npmjs.com/package/@vitejs/plugin-react fixed issue. Cheers!
