### ISSUE TITLE
Type Error 'Valid Route Paths' when using useNavigate on nested routes

### ISSUE THREAD

**Issue by bsell93** [TanStack/router#630]
### Describe the bug

Getting type error `Error 'Valid Route Paths'` when attempting to use `useNavigate` to navigate to a child route. May be related to #555 

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-fx77y7?file=src%2Froutes%2Fdashboard%2Finvoices%2Finvoice.tsx

Specifically line 92

### Steps to Reproduce the Bug or Issue

1. Create parent & child routes
2. Use navigate

### Expected behavior

Not to see type error

### Screenshots or Videos

<img width="844" alt="image" src="https://github.com/TanStack/router/assets/5335177/08797df7-4c60-4c03-b3fa-704409055ae0">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: 0.0.1-beta.100

**Comment by lorenzocorallo** [comment]
I faced this issue too and actually didn't find any solution

**Comment by tannerlinsley** [comment]
The trailing slash on `fullPath` was not matching up with the latest fixes for resolving index routes. This is now fixed by using the `route.to` property instead of `fullPath` or `id`. Examples have been updated.

- `id`: The ID of the route, including layout route identifiers and wildcards
- `fullPath`: The full path of the route, including trailing slashes so as to differentiate index routes from their parents
- `to`: The navigable full path of the route without any trailing slashes.

**Comment by hosmelq** [comment]
@tannerlinsley I'm getting an error when I use the `route.to` property.

```js
navigate({
  params: {
    organizationId: data.data.id,
  },
  replace: true,
  to: organizationsRootRoute.to,
})
```

```
Argument of type '{ params: { organizationId: string; }; replace: true; to: "/$organizationId"; }' is not assignable to parameter of type 'MakeLinkOptions<"/onboarding/", "/$organizationId">'.
  Property 'search' is missing in type '{ params: { organizationId: string; }; replace: true; to: "/$organizationId"; }' but required in type '{ search: SearchReducer<Partial<{}>, unknown>; }'.
```

**Comment by tannerlinsley** [comment]
Can you send me a CodeSandBox or stackblitz link please?

**Comment by tannerlinsley** [comment]
Please double check that your routes are referencing the correct parentRoute.

**Comment by hosmelq** [comment]
Ok, I'll check. Thank You!
