### ISSUE TITLE
Navigation lifecycle

### ISSUE THREAD

**Issue by fnn** [TanStack/router#649]
### Describe the bug

I think the current navigation lifecycle is not correct. When navigate away from a page with params you will lose the params during pending state and the old page will render even when the router is in idle state again and the current location is the new page. This behavior was different a few betas ago.

### Your Example Website or App

https://stackblitz.com/edit/github-9lqgst?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to StackBlitz example
2. Open console
3. Click on "Go to details page"
4. Click on "Go to list page"
5. Look at console output

Console output:
```
params: 123; status: idle; currentLocation: /123                                main.tsx:38
params: undefined; status: pending; currentLocation: /123             main.tsx:38
params: undefined; status: idle; currentLocation: /                           main.tsx:38
```

### Expected behavior

Here is a StackBlitz with beta 83: https://stackblitz.com/edit/github-9lqgst-payc5c?file=src%2Fmain.tsx

The same steps will lead to the following console output:
```
params: 123; status: idle; currentLocation: /123                                main.tsx:38
params: 123; status: pending; currentLocation: /123                        main.tsx:38
```

It will keep the params during pending state and the second idle state is not rendered on the old component.

### Screenshots or Videos

![image](https://github.com/TanStack/router/assets/5686051/ed980e0b-2ed5-48ae-a6e2-9bb072f81a61)

### Platform

- OS: Linux
- Browser: Chrome
- Version: 115.0.5790.90
- @tanstack/router: 0.0.1-beta.108

**Comment by tannerlinsley** [comment]
Working on this next. Stay tuned.

**Comment by tannerlinsley** [comment]
This is turning out to be a difficult one. Mainly because we are managing state outside of react and bridging it in with useSyncExternalStore, so React.startTransition doesn't really do much here. I originally had the separate pending states, then got rid of them, which is the effect you're seeing here. I either need to figure out how to get uSES working with startTransition, figure out how to get useDeferred to operate the way I want, or just go back to a separate pending state (but that would mess with Suspense for sure.

**Comment by tannerlinsley** [comment]
This will be fixed in the next release. I'm happy to say that the new logs for navigating in and out of that component are:

```
params: 123; status: idle; currentLocation: /123
```

🎉
