### ISSUE TITLE
loaderDeps is not called with validated search params

### ISSUE THREAD

**Issue by schiller-manuel** [TanStack/router#858]
### Describe the bug

`loaderDeps()` is not called with the output of `validateSearch()`

### Your Example Website or App

https://codesandbox.io/p/devbox/gracious-shockley-zcttxs?file=%2Fsrc%2Fmain.tsx%3A230%2C1

### Steps to Reproduce the Bug or Issue

1. go to https://codesandbox.io/p/devbox/gracious-shockley-zcttxs?file=%2Fsrc%2Fmain.tsx%3A230%2C1
2. click on the "missing-post-id" link
3. `{"postId":"undefined"}` is shown

### Expected behavior

`loaderDeps()` should be called with the result of `validateSearch()`

In the above example this would mean that if the postId query param is missing, zod will default to `1` and thus `{"postId": "1"}` should be shown.

### Platform

- OS: macOS
- Browser: Firefox
- Version: 120

**Comment by tannerlinsley** [comment]
Using the latest version, I found that loaderDeps is now always up to date and always using the validated search result. One thing you'll want to note is that `z.coerce.string().catch('1')(undefined)` will actually coerce `undefined` to `'undefined'` and not catch (since it is a string). What you likely want is: `z.string().catch('1')`, which will throw on `undefined` and use your catch value of `1` :)
